<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.9</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.core.ai</groupId>
	<artifactId>CoreAI</artifactId>
	<version>${dependency.version}</version>
	<name>CoreAI</name>
	<description>Demo project for Spring Boot</description>
	<url/>
    <packaging>jar</packaging>

	<properties>
		<java.version>17</java.version>
		<spring-ai.version>1.1.2</spring-ai.version>
        <jar.name>core-ai</jar.name>
        <dependency.version>v1-Duel-LLM</dependency.version>
    </properties>
	<dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>org.springframework.ai</groupId>-->
<!--			<artifactId>spring-ai-advisors-vector-store</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-model-openai</artifactId>
		</dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-mcp-client</artifactId>
        </dependency>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-starter-vector-store-pinecone</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

<!--	<build>-->

<!--        <finalName> ${jar.name}</finalName>-->
<!--            <plugins>-->
<!--                <plugin>-->
<!--                    <groupId>org.apache.maven.plugins</groupId>-->
<!--                    <artifactId>maven-compiler-plugin</artifactId>-->
<!--                    <configuration>-->
<!--                        <annotationProcessorPaths>-->
<!--                            <path>-->
<!--                                <groupId>org.projectlombok</groupId>-->
<!--                                <artifactId>lombok</artifactId>-->
<!--                            </path>-->
<!--                        </annotationProcessorPaths>-->
<!--                    </configuration>-->
<!--                </plugin>-->
<!--                <plugin>-->
<!--                    <groupId>org.springframework.boot</groupId>-->
<!--                    <artifactId>spring-boot-maven-plugin</artifactId>-->
<!--                    <configuration>-->
<!--                        <excludes>-->
<!--                            <exclude>-->
<!--                                <groupId>org.projectlombok</groupId>-->
<!--                                <artifactId>lombok</artifactId>-->
<!--                            </exclude>-->
<!--                        </excludes>-->
<!--                    </configuration>-->
<!--                </plugin>-->


<!--                <plugin>-->
<!--                    <groupId>org.apache.maven.plugins</groupId>-->
<!--                    <artifactId>maven-jar-plugin</artifactId>-->
<!--                    <configuration>-->
<!--                        &lt;!&ndash; DO NOT include log4j.properties file in your Jar &ndash;&gt;-->
<!--                        <excludes>-->
<!--                            <exclude>**/log4j.properties</exclude>-->
<!--                        </excludes>-->
<!--                        <archive>-->
<!--                            <manifest>-->
<!--                                &lt;!&ndash; Jar file entry point &ndash;&gt;-->
<!--                                <mainClass>com.core.ai.CoreAI.CoreAiApplication</mainClass>-->
<!--                            </manifest>-->
<!--                        </archive>-->
<!--                    </configuration>-->
<!--                </plugin>-->
<!--                <plugin>-->
<!--                    <groupId>io.fabric8</groupId>-->
<!--                    <artifactId>docker-maven-plugin</artifactId>-->
<!--                    <version>0.38.1</version>-->
<!--                    <executions>-->
<!--                        <execution>-->
<!--                            <id>build</id>-->
<!--                            <phase>pre-integration-test</phase>-->
<!--                            <goals>-->
<!--                                <goal>build</goal>-->
<!--                            </goals>-->
<!--                        </execution>-->
<!--                    </executions>-->
<!--                    <configuration>-->

<!--                        <buildArgs>-->
<!--                            <JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>-->
<!--                        </buildArgs>-->
<!--                    </configuration>-->
<!--                </plugin>-->
<!--            </plugins>-->





<!--	</build>-->

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
